project:
  type: website
  output-dir: ../_site

website:
  title: "Traffic Accident Severity"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cosmo
    toc: true
    lang: en

